[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = { sepolia = "https://api.zan.top/node/v1/eth/sepolia/public", optimism_goerli = "https://optimism-goerli.publicnode.com", base_goerli = "https://base-goerli.public.blastapi.io", arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc" }

# Sepolia	11155111
# Base Goerli	84531
# Optimism Goerli	420
# Arbitrum Sepolia	421614
